/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://wexs4zkc5bb6fbqv2aihyhsejm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ud5bx4eomrcovpluyxfmkoeyhe",
    "aws_cognito_identity_pool_id": "us-east-1:3734cc13-f8e5-4ed3-9794-86c73e32ffc8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_k7GgKDyWL",
    "aws_user_pools_web_client_id": "4akqp9cu02kgn02b1l1ui9dnqt",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "firmfiles212400-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_content_delivery_bucket": "carerunners-20230918165809-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://dbnmrfsutioun.cloudfront.net"
};


export default awsmobile;
